<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\TaskTracker.Application.Dto\TaskTracker.Application.Dto.csproj" />
      <ProjectReference Include="..\TaskTracker.Application.Interface\TaskTracker.Application.Interface.csproj" />
      <ProjectReference Include="..\TaskTracker.Domain.Interface\TaskTracker.Domain.Interface.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="15.0.1" />
    </ItemGroup>

</Project>
