services:
  tasktracker:
    build:
      context: .
      dockerfile: TaskTracker.Presentation/Dockerfile
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: tasktracker
      POSTGRES_PASSWORD: todo789
      POSTGRES_DB: tasktracker_db
    ports:
      - "5431:5432"
    volumes:
      - tasktracker_data:/var/lib/postgresql/data
volumes:
  tasktracker_data:

