<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2"/>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="TaskTracker.Domain\Class1.cs">
        <Link>TaskTracker.Core\Class1.cs</Link>
      </Compile>
      <Compile Update="TaskTracker.Infrastructure\AppDbContext.cs">
        <Link>TaskTracker.Infraestructure\AppDbContext.cs</Link>
      </Compile>
      <Compile Update="TaskTracker.Infrastructure\DependencyInjection\ServiceCollectionExtensions.cs">
        <Link>TaskTracker.Infraestructure\DependencyInjection\ServiceCollectionExtensions.cs</Link>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <Folder Update="TaskTracker.Infrastructure\DependencyInjection" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="TaskTracker.Infrastructure\TaskTracker.Infrastructure.csproj" />
    </ItemGroup>

</Project>
